[project]
name = "healthcare-project"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "colorama==0.4.6",
    "iniconfig==2.3.0",
    "numpy==2.4.2",
    "packaging==26.0",
    "pandas==3.0.1",
    "pluggy==1.6.0",
    "pygments==2.19.2",
    "pytest==9.0.2",
    "python-dateutil==2.9.0.post0",
    "six==1.17.0",
    "tzdata==2025.3",
]
